SISIFO2019.Mvc/Controllers/OrdenesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SISIFO2019.Data;
using SISIFO2019.Model;

namespace SISIFO2019.Mvc.Controllers
{
    public class OrdenesController : Controller
    {
        private readonly InstalacionesContext _context;

        public OrdenesController(InstalacionesContext context)
        {
            _context = context;
        }

        // GET: Ordenes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ordenes
                .OrderBy(o => o.Cliente)
                .ToListAsync());
        }

        // GET: Ordenes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordenCRM = await _context.Ordenes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ordenCRM == null)
            {
                return NotFound();
            }

            return View(ordenCRM);
        }

        // GET: Ordenes/Create
        public IActionResult Create(int? instalacionId = null)
        {

            if (instalacionId == null)
            {
                return View();
            }

            return View(new OrdenCRM(){InstalacionId = instalacionId});
        }

        // POST: Ordenes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,InstalacionId,Cliente,Direccion,Partido,NumeroOrden,NumeroEnlace,FechaInicio,FechaCierre,Tipo,CRM")] OrdenCRM ordenCRM)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ordenCRM);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ordenCRM);
        }

        // GET: Ordenes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordenCRM = await _context.Ordenes.FindAsync(id);
            if (ordenCRM == null)
            {
                return NotFound();
            }
            return View(ordenCRM);
        }

        // POST: Ordenes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,InstalacionId,Cliente,Direccion,Partido,NumeroOrden,NumeroEnlace,FechaInicio,FechaCierre,Tipo,CRM")] OrdenCRM ordenCRM)
        {
            if (id != ordenCRM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ordenCRM);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdenCRMExists(ordenCRM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ordenCRM);
        }

        // GET: Ordenes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordenCRM = await _context.Ordenes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ordenCRM == null)
            {
                return NotFound();
            }

            return View(ordenCRM);
        }

        // POST: Ordenes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ordenCRM = await _context.Ordenes.FindAsync(id);
            _context.Ordenes.Remove(ordenCRM);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdenCRMExists(int id)
        {
            return _context.Ordenes.Any(e => e.Id == id);
        }
    }
}

SISIFO2019.Mvc/Controllers/SitiosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SISIFO2019.Mvc.Controllers
{
    public class SitiosController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

SISIFO2019.Mvc/Controllers/TareasController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SISIFO2019.Data;
using SISIFO2019.Model;
using SISIFO2019.Mvc.Models.Tareas;

namespace SISIFO2019.Mvc.Controllers
{
    public class TareasController : Controller
    {
        private readonly InstalacionesContext _context;

        public TareasController(InstalacionesContext context)
        {
            _context = context;
        }

        // GET: Tareas
        public async Task<IActionResult> Index()
        {
            return View("TareasAgrupadasPorFecha", await _context.Tareas
                .OrderBy(t => t.FechaInicio)
                .Select(tarea => new TareaViewModel(tarea))
                .ToListAsync());
        }

        // GET: Tareas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarea = await _context.Tareas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tarea == null)
            {
                return NotFound();
            }

            return View(tarea);
        }

        // GET: Tareas/Create
        public IActionResult Create(int? instalacionId)
        {
            if (instalacionId == null)
            {
                return View();
            }
            return View(new CrearTareaViewModel(){InstalacionId = instalacionId.Value});
        }

        // POST: Tareas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,InstalacionId,FechaInicio,FechaFin,Tipo,Contratista,Descripcion,Estado,DuracionHoras,DuracionMinutos")] CrearTareaViewModel crearTareaViewModel)
        {
            if (ModelState.IsValid)
            {

                var fechaInicio = crearTareaViewModel.FechaInicio;

                var fechaFin = fechaInicio.Value;
                fechaFin = fechaFin.AddHours(crearTareaViewModel.DuracionHoras);
                fechaFin = fechaFin.AddMinutes(crearTareaViewModel.DuracionMinutos);

                var tarea = new Tarea()
                {
                    Id = crearTareaViewModel.Id,
                    InstalacionId = crearTareaViewModel.InstalacionId,
                    FechaInicio = crearTareaViewModel.FechaInicio,
                    FechaFin = fechaFin,
                    Tipo = crearTareaViewModel.Tipo,
                    Contratista = crearTareaViewModel.Contratista,
                    Descripcion = crearTareaViewModel.Descripcion,
                    Estado = crearTareaViewModel.Estado
                };

                //var tarea = _mapper.Map<Tarea>(crearTareaViewModel);
                _context.Add(tarea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            crearTareaViewModel.InstalacionId = 0;
            return View(crearTareaViewModel);
        }

        // GET: Tareas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarea = await _context.Tareas.FindAsync(id);
            if (tarea == null)
            {
                return NotFound();
            }
            return View(tarea);
        }

        // POST: Tareas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,InstalacionId,FechaInicio,FechaFin,Tipo,Contratista,Descripcion,Estado")] Tarea tarea)
        {
            if (id != tarea.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TareaExists(tarea.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tarea);
        }

        // GET: Tareas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarea = await _context.Tareas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tarea == null)
            {
                return NotFound();
            }

            return View(tarea);
        }

        // POST: Tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tarea = await _context.Tareas.FindAsync(id);
            _context.Tareas.Remove(tarea);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TareaExists(int id)
        {
            return _context.Tareas.Any(e => e.Id == id);
        }
    }
}

SISIFO2019.Mvc/Views/Shared/_FormGroup.cshtml
@using System.Security.Cryptography.X509Certificates

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Property

<div class="form-group row">
    <label asp-for=PropertyName class="control-label col-3 col-form-label"></label>
    <div class="col-9">
        <input asp-for=@Model.PropertyName class="form-control" />
        <span asp-validation-for=@Model.PropertyName class="text-danger"></span>
    </div>
</div>

SISIFO2019.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SISIFO2019</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SISIFO2019</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Instalaciones" asp-controller="Home" asp-action="Index">Instalaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ordenes" asp-action="Index">Ordenes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tareas" asp-action="Index">Tareas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sitios" asp-action="Index">Sitios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-1">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SISIFO2019 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)

</body>
</html>